---
- name: Flask App Setup
  hosts: servers
  become: True
  vars:
    _PROJECT_DIR_: /home/user/flask-number-store
  tasks:
    # - name: install python-aptitude
    #   apt:
    #     name: python3-apt
    #     update_cache: yes

    # - name: add repository for python upgrade
    #   apt_repository:
    #     repo: ppa:deadsnakes/ppa

    # - name: install python3.8
    #   apt:
    #     name: python3.8
    #     update_cache: yes

    # - name: Alternatives link created for python3.8
    #   alternatives:
    #     name: python3
    #     link: /usr/bin/python3
    #     path: /usr/bin/python3.8

    # - name: Correct python3 alternative is selected
    #   alternatives:
    #     name: python3
    #     path: /usr/bin/python3.8

    - name: Install dependencies and other packages
      apt: name={{ item }} update_cache=yes cache_valid_time=360
      loop:
        - git
        - python3-pip
        - python3-dev
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3-setuptools
        - python3-venv

    - name: Clone flask project from GitHub
      git:
        repo: 'https://github.com/pushkarsharma/flask-number-store.git'
        dest: {{ _PROJECT_DIR_ }}
        clone: yes
        update: yes

    - name: Create virtual environment for the project
      shell: python3 -m venv {{ _PROJECT_DIR_ }}
      args:
        creates: {{ _PROJECT_DIR_ }}/bin

    - name: Install requirements into virtual environment
      pip:
        requirements: {{ _PROJECT_DIR_ }}/requirements.txt
        virtualenv: {{ _PROJECT_DIR_ }}

    - name: Update configuration files with project directory
      shell: sed -i 's|_PROJECT_DIR_|{{ _PROJECT_DIR_ }}|g' {{ _PROJECT_DIR_ }}/configurations/*