---
- name: Flask App Setup
  hosts: servers
  vars:
    _PROJECT_DIR_: /home/user/flask-number-store
  tasks:
    - name: Install dependencies and other packages
      apt: name={{ item }} update_cache=yes cache_valid_time=360
      loop:
        - git
        - libpcre3
        - libpcre3-dev
        - python3-pip
        - python3-dev
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3-setuptools
        - python3-venv
        - nginx
      become: true

    - name: Clone flask project from GitHub
      git:
        repo: 'https://github.com/pushkarsharma/flask-number-store.git'
        dest: "{{ _PROJECT_DIR_ }}"
        clone: yes
        update: yes

    - name: Create virtual environment for the project
      shell: python3 -m venv {{ _PROJECT_DIR_ }}
      args:
        creates: "{{ _PROJECT_DIR_ }}/bin"

    - name: Install requirements into virtual environment
      pip:
        requirements: "{{ _PROJECT_DIR_ }}/requirements.txt"
        virtualenv: "{{ _PROJECT_DIR_ }}"

    - name: Collect all configuration files fot the next update
      find:
        paths: "{{ _PROJECT_DIR_ }}/configurations/"
        patterns: "*"
      register: config_files

    - name: Replace configuration files with project directory
      replace:
        path: "{{ item.path }}"
        regexp: "_PROJECT_DIR_"
        replace: "{{ _PROJECT_DIR_ }}"
      loop: "{{ config_files.files }}"

    - name: Copy numSave service config file to systemd
      copy:
        src: "{{ _PROJECT_DIR_ }}/configurations/numSave.service"
        dest: "/etc/systemd/system/"
        remote_src: yes
        mode: '0777'
      become: true

    - name: Start numSave service
      systemd:
        name: numSave
        state: started
        enabled: yes
        daemon_reload: yes
      become: true

    - name: Copy nginx config file
      copy:
        src: "{{ _PROJECT_DIR_ }}/configurations/numSave"
        dest: "/etc/nginx/sites-available/"
        remote_src: yes
        mode: '0644'
      become: true
    
    - name: Create symbolic link for Nginx
      file:
        src: /etc/nginx/sites-available/numSave
        dest: /etc/nginx/sites-enabled/numSave
        state: link
      become: true

    - name: Restart Nginx service
      systemd:
        name: nginx
        state: restarted
        daemon_reload: yes
      become: true

    - name: Adjust firewall for Nginx
      ufw:
        name: Nginx Full
        rule: allow
      become: true