---
- name: MariaDB Setup
  hosts: servers
  become: true
  vars:
    mysql_root_password: root
  tasks:
    - name: Install dependencies and MariaDB
      apt: name={{ item }} update_cache=yes cache_valid_time=360
      loop:
        - python3-pymysql
        - mariadb-server

    # - name: Fetch root password from .my.cnf
    #   mysql_user:
    #     name: 
    #     password: 

    # - name: Set the root credentials by copying file
    #   copy:
    #     src: "{{ _PROJECT_DIR_ }}/configurations/.my.cnf"
    #     dest: "/home/user/"
    #     remote_src: yes
    #     mode: '0777'
    #   become: true

    - name: Set root user password
      # If .my.cnf already exists, this will cause an mysql-root-password update.
      mysql_user:
        name: root
        password: "{{ mysql_root_password}}"
        check_implicit_admin: true

    - name: Create .my.cnf
      template:
        src: "templates/client.my.cnf.j2"
        dest: "/home/user/.my.cnf"
        owner: root
        group: root
        mode: 0600

    - name: Remove anonymous user account for localhost
      mysql_user:
        name: ''
        host: localhost
        state: absent

    - name: Create user with name 'user' with all database privileges
      mysql_user:
        name: user
        password: password
        priv: '*.*:ALL'
        state: present

    - name: Delete 'test' database
      mysql_db:
        name: test
        state: absent

    - name: Create 'number-storage' database
      mysql_db:
        name: number-storage
        state: present